name: docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build docs
        run: |
          yarn install
          yarn run docs

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages # The branch the action should deploy to.
          PUBLISH_DIR: ./docs # The folder the action should deploy.
