name: publish

on: create

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
      - run: npm run publish
